{{ if .Values.regexmatches }}
kind: ConfigMap
apiVersion: v1
metadata:
  name: {{ include "reddit-exporter.fullname" . }}-config
  labels:
    app.kubernetes.io/name: {{ include "reddit-exporter.name" . }}
    helm.sh/chart: {{ include "reddit-exporter.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
data:
  regexfile.{{ .Values.regexMatchesFormat }}: |
{{ .Values.regexMatches | indent 4 }}
{{ end }}