apiVersion: apps/v1beta2
kind: Deployment
metadata:
  name: {{ include "reddit-exporter.fullname" . }}
  labels:
    app.kubernetes.io/name: {{ include "reddit-exporter.name" . }}
    helm.sh/chart: {{ include "reddit-exporter.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  replicas: {{ .Values.replicaCount }}
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "reddit-exporter.name" . }}
      app.kubernetes.io/instance: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ include "reddit-exporter.name" . }}
        app.kubernetes.io/instance: {{ .Release.Name }}
      annotations:
        checksum/config: {{ include (print $.Template.BasePath "/config.yaml") . | sha256sum }}
    spec:
{{- if .Values.regexmatches }}
      volumes:
        - name: reddit-exporter-config
          configMap:
            name: {{ include "reddit-exporter.fullname" . }}-config
{{- end }}
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          args:
{{- range .Values.subreddits }}
            - -s 
            - {{ . }}
{{ else }}
            - {{required "List of subreddits is required" .Values.blah }}
{{- end }}
{{- if .Values.verbose }}
            - -v
{{- end }}
{{- if .Values.regexmatches }}
            - --regexfile=/config/regexfile.{{ .Values.regexMatchesFormat }}
{{- end }}
          ports:
            - name: metrics
              containerPort: 8000
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /metrics
              port: metrics
          readinessProbe:
            httpGet:
              path: /metrics
              port: metrics
{{- if .Values.regexmatches }}
          volumeMounts:
            - name: reddit-exporter-config
              mountPath: /config/
{{- end }}
          resources:
{{ toYaml .Values.resources | indent 12 }}
    {{- with .Values.nodeSelector }}
      nodeSelector:
{{ toYaml . | indent 8 }}
    {{- end }}
    {{- with .Values.affinity }}
      affinity:
{{ toYaml . | indent 8 }}
    {{- end }}
    {{- with .Values.tolerations }}
      tolerations:
{{ toYaml . | indent 8 }}
    {{- end }}
